baseURL = 'https://mattesschu.github.io/'
languageCode = 'en-us'
title = 'Greetings from northern germany'
theme = "PaperMod"
paginate = 5
enableRobotsTXT = true

[taxonomies]
category = 'categories'
tag = 'tags'

[params]
env = "production"
description = "Personal Programming projects without Schnickschnack."
author = "MattesSchu"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
images = [ "papermod-cover.png" ]

[params.profileMode]
enabled = false
title = "MattesSchu"
imageUrl = "#"
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Archives"
url = "archives"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags/"

[params.homeInfoParams]
Title = "Moin"
Content = """
Personal Programming projects without Schnickschnack.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/mattesschu/"

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "projects/"
weight = 10

[menu]
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "tags/"
weight = 30

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "archives"
weight = 40

[[menu.main]]
identifier = "search"
name = "Search"
url = "search/"
weight = 50

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/mattesschu"
weight = 60

[outputs]
home = [ "HTML", "RSS", "JSON" ]
